"use strict";window.Kar=function(fileInfo){var buffer=fileInfo.buffer;var entries=[];var empty={"key":"","path":"","offset":0,"size":0,"buffer":new ArrayBuffer(),"deflateLevel":0};var password="";var timestemp=0;var deflateLevel=0;var table=new Int32Array(624);var status=0;var getPasswordMD5=function(t){return new MD5(new ArrayBuffer().fromText(t)).getString(false,false);};var getPassword=function(){var md5=(arguments.length>0?arguments[0]:"");var m={"keel.dat":"dhfuhsudfh98vhdsovnfdhiouer8u8hgjbkjciudsuifsjdiosajfn","launch.dat":"dhfuhsudfh98vhdsovnfdhiouer8u8hgjbkjciudsuifsjdiosajfn","amped.kar":"program_getamped","tool.kar":"program_getamped_tool","exportskin":"exportskin","resource.kar":"resource_getamped","dists":"dists_getamped","autoupdate.kar":"updateupdateupdate","cache.kar":"cachecachecache","client":"go;agupajenbapehaeso;gal;etgjn","defs.kar":"linkdefinitions","enter.kar":"enterenterenter","guildicon.kar":"guildiconguildiconguildicon","kdj.kar":"kdjdkdjdkdjdkdj","offlineskin.kar":"offlineskinofflineskinofflineskin","setting.kar":"setting","linkdata.kar":"linkdatahogehoge","dungeon.kar":"linkdatahogehoge","free.kar":"shop_getamped",".skin":"skinskinskin",".hskin":"skinskinskin",".hhskin":"skinskinskin",".repkar":"yalperyalperyalper",".omd":"mdmdmd",".ssoa":"soasoasoa"};var checkPassword=function(t){return getPasswordMD5(t)==md5;};var filename=fileInfo.nameCore+"."+fileInfo.extension[0];if(md5){if(!isUndefined(m[filename])&&checkPassword(m[filename])){return m[filename];}
else{for(var n in m){if((n!=filename)&&(checkPassword(m[n]))){return m[n];}}
var v=fileInfo.nameCore.repeat(3);if(checkPassword(v)){return v;}
else if(window.Kar_guess){return window.Kar_guess(md5);}}}
else{if(!isUndefined(m[filename])){return m[filename];}
else{for(var n in m){if(filename.endsWith(n)){return m[n];}}
for(var n in m){if(filename.startsWith(new FileInfo(n).nameCore)){return m[n];}}}
return fileInfo.nameCore.repeat(3);}};var init=function(s){for(status=0;status<table.length;status++){table[status]=(status?(0x00010DCD*table[status-1]):s);}};var getMask=function(){var r=new Int32Array(1);var m=[0,0x9908B0DF];if(status>=624){for(var i=0;i<table.length;i++){r[0]=(table[i]&0x80000000)|(table[(i+1)%table.length]&0x7FFFFFFF);table[i]=table[(i+397)%table.length]^(r[0]>>>1)^m[r[0]&1];}
status=0;}
r[0]=table[status++];r[0]^=(r[0]>>>11);r[0]^=(r[0]<<7)&0x9D2C5680;r[0]^=(r[0]<<15)&0xEFC60000;r[0]^=(r[0]>>>18);return r[0]>>>24;};var decrypt=function(bf,s){var r=new ArrayBuffer(bf.byteLength);if(s){init(s);for(var i=0;i<r.byteLength;i++){r.setUint8(bf.getUint8(i)^getMask(),i);}}
return r;};var indexOf=function(path){for(var i=0;i<entries.length;i++){if(entries[i]["path"]==path){return i;}}
return-1;};var getFolders=function(path){var r=[];var s=0;while(true){var l=path.indexOf("/",s);if(l>0){r.push((r.length?r[r.length-1]:"")+path.slice(s,l+1));s=l;}
s+=1;if(l==-1){break;}}
return r;};var add=function(file){if(file["path"]){while(file["path"][0]=="/"){file["path"]=file["path"].slice(1);}
var n=-1;var l=indexOf(file["path"]);if(l!=-1){n=l;entries[n]["key"]=file["key"];entries[n]["offset"]=file["offset"]||entries[n]["offset"]||empty["offset"];entries[n]["size"]=file["size"]||entries[n]["size"]||empty["size"];entries[n]["buffer"]=file["buffer"]||entries[n]["buffer"]||empty["buffer"];entries[n]["deflateLevel"]=file["deflateLevel"]||file["deflateLevel"]||(!isUndefined(entries[n]["deflateLevel"])?entries[n]["deflateLevel"]:empty["deflateLevel"]);}
else{n=entries.length;entries[n]={"index":n,"key":file["key"],"path":file["path"],"folders":getFolders(file["path"]),"offset":file["offset"]||empty["offset"],"size":file["size"]||empty["size"],"buffer":file["buffer"]||empty["buffer"],"deflateLevel":(!isUndefined(file["deflateLevel"])?file["deflateLevel"]:0)};}
var f=[];for(var i=0;i<entries[n]["folders"].length;i++){var l=indexOf(entries[n]["folders"][i]);if(l==-1){f.push({"index":entries.length,"key":empty["key"],"path":entries[n]["folders"][i],"folders":getFolders(entries[n]["folders"][i]),"offset":entries[n]["offset"],"size":0,"buffer":empty["buffer"],"deflateLevel":empty["deflateLevel"]});}}
if(f.length){entries.inserts(f,n);}}};var checkBuffer=function(index){if(!entries[index]["buffer"].byteLength&&!isUndefined(entries[index]["key"])){entries[index]["key"]=entries[index]["key"]||(password?password+"/"+entries[index]["key"]+timestemp:timestemp.toString());entries[index]["deflateLevel"]=entries[index]["deflateLevel"]||deflateLevel;entries[index]["buffer"]=decrypt(buffer.getBuffer(entries[index]["offset"],entries[index]["size"]),entries[index]["key"].hashCodeJava());entries[index]["buffer"]=(entries[index]["deflateLevel"]?entries[index]["buffer"].inflate():entries[index]["buffer"]);}
return entries[index]["buffer"];};var clearBuffer=function(){if(buffer.byteLength){for(var i=0;i<entries.length;i++){checkBuffer(i);}
buffer=new ArrayBuffer();}};var toBuffer=function(){password=getPassword();var passwordMD5=getPasswordMD5(password);for(var i=0;i<entries.length;i++){entries[i]["key"]=(password?password+"/"+entries[i]["path"]+timestemp:timestemp.toString());entries[i]["deflateLevel"]=deflateLevel;}
var headerOffset=4;var list=(function(){var v=[];for(var i=0;i<entries.length;i++){v.push({"path":"/"+entries[i]["path"],"bytes":(entries[i]["deflateLevel"]?entries[i]["buffer"].deflate("zlib",-1):entries[i]["buffer"]),"offset":headerOffset});headerOffset+=v[v.length-1]["bytes"].byteLength;}
return v;})();var getHeaderBuffer=function(){var ex=(fileInfo.nameCore+"."+fileInfo.extension[0]=="launch.dat");var bf1=(function(){var l=2+passwordMD5.length+8;var bw=new BufferWriter(l);bw.writeUTFJava(passwordMD5);bw.writeLongJava(timestemp);return bw.toBuffer();})();var bfd=(function(){var deflateString=(deflateLevel?"deflate,dlv="+deflateLevel+",":"");if(deflateString){var bw=new BufferWriter(3+deflateString.length);bw.writeByteJava(0x74);bw.writeUTFJava(deflateString);return bw.toBuffer();}
else{return new ArrayBuffer().fromArray([0x70]);}})();var bf2=(function(){var l=4+list.reduce(function(t,a){return t+(2+a["path"].length)*2+4+8;},0);var bw=new BufferWriter(l);bw.writeIntJava(list.length);for(var i=0;i<list.length;i++){bw.writeUTFJava(list[i]["path"]);bw.writeUTFJava(list[i]["path"]);bw.writeIntJava(list[i]["bytes"].byteLength);bw.writeLongJava(list[i]["offset"]);}
return bw.toBuffer();})();var bfs=new ArrayBuffer().fromArray([0xAC,0xED,0x00,0x05]);var bfp=new ArrayBuffer();if(ex){bf2=new ArrayBuffer().concat(new ArrayBuffer().fromArray([1]),bf1,new ArrayBuffer().fromArray(bfd.byteLength>1?[1]:[0]),bf2);}
else{var bw=new BufferWriter(2+bf1.byteLength+bfd.byteLength);bw.writeByteJava(0x77);bw.writeUint(1,bf1.byteLength);bw.writeBuffer(bf1);bw.writeBuffer(bfd);bfp=bw.toBuffer();}
return new ArrayBuffer().concat(bfs,bfp,bf2.toBlockDataJava());};var headerBuffer=getHeaderBuffer();if(!deflateLevel&&(headerOffset+headerBuffer.byteLength>0x7FFFFFFF)){deflateLevel=1;headerOffset=4;for(var i=0;i<entries.length;i++){entries[i]["deflateLevel"]=deflateLevel;list[i]["bytes"]=(entries[i]["deflateLevel"]?entries[i]["buffer"].deflate("zlib",-1):entries[i]["buffer"]);headerOffset+=v[v.length-1]["bytes"].byteLength;}
headerBuffer=getHeaderBuffer();}
for(var i=0;i<entries.length;i++){list[i]["bytes"]=decrypt(list[i]["bytes"],entries[i]["key"].hashCodeJava());}
var bw=new BufferWriter(headerOffset+headerBuffer.byteLength);bw.writeIntJava(headerBuffer.byteLength^0x85FD91A1);for(var i=0;i<list.length;i++){bw.writeBuffer(list[i]["bytes"]);}
bw.writeBuffer(decrypt(headerBuffer,headerOffset.toString().hashCodeJava()));return bw.toBuffer();};var addFiles=function(files){for(var i=0;i<files.length;i++){add(files[i]);}
if(entries.length){if(!entries.find(function(a){return a["path"]=="";})){entries.unshift({"path":"","buffer":new ArrayBuffer()});}}
entries=entries.sort(SortPath);for(var i=0;i<entries.length;i++){entries[i]["index"]=i;}
return this;};this.addFiles=function(files){addFiles(files);clearBuffer();return this;};this.addFile=function(file){this.addFiles([file]);return this;};this.checkBuffer=checkBuffer;this.getEntries=function(){return entries;};this.from=function(buffer){var files=[];var headerSize=buffer.getInt32(0,false)^0x85FD91A1;var headerOffset=buffer.byteLength-headerSize;var headerBuffer=decrypt(buffer.getBuffer(headerOffset,headerSize),headerOffset.toString().hashCodeJava());var ser=headerBuffer.unserializeSer();if(ser.length==3){var l=(ser[1]&&ser[1].indexOf("deflate")!=-1?parseInt(ser[1].extract("dlv=",","))||0:0);if(!l){l=(ser[1]&&ser[1].indexOf("deflate")!=-1?parseInt(ser[1].extract("deflate=",","))||0:0);if(l){ser[0]=ser[0].getBuffer(2,ser[0].byteLength-3);}}
ser[1]=new ArrayBuffer().fromArray([l]);ser=new ArrayBuffer().concat.apply(new ArrayBuffer(),ser);}
else{ser=ser.getBuffer(1);}
var br=new BufferReader(ser);var passwordMD5=br.readUTFJava();password=getPassword(passwordMD5);timestemp=br.readLongJava();deflateLevel=br.readByteJava();var fileCount=br.readIntJava();for(var i=0;i<fileCount;i++){files.push({"index":i,"key":br.readUTFJava(),"path":br.readUTFJava(),"size":br.readIntJava(),"offset":br.readLongJava(),"deflateLevel":deflateLevel});}
for(var i=0;i<files.length;i++){files[i]["key"]=(!isUndefined(password)?(password?password+files[i]["key"]+timestemp:timestemp.toString()):undefined);}
entries=[];addFiles(files);return this;};this.to=function(){var option=(arguments.length>0?arguments[0]:{});option=option||{};var newDeflateLevel=(!isUndefined(option["deflateLevel"])?option["deflateLevel"]:deflateLevel);var isNewTimestemp=(!isUndefined(option["isNewTimestemp"])?option["isNewTimestemp"]:true);if((deflateLevel!=newDeflateLevel)||isNewTimestemp){clearBuffer();if(deflateLevel!=newDeflateLevel){deflateLevel=newDeflateLevel;}
if(isNewTimestemp){timestemp=new Date().getTime();}}
buffer=(buffer.byteLength?buffer:toBuffer());return buffer;};if(buffer.byteLength){this.from(buffer);}};window.Dat=window.Kar;window.Repkar=window.Kar;window.Skin=window.Kar;window.Hskin=window.Kar;window.Hhskin=window.Kar;window.Omd=window.Kar;window.Ssoa=window.Kar;SupportPkg.add("kar","dat","repkar","skin","hskin","hhskin","omd","ssoa");UpdateAccept();OutputPkg.add("kar","dat","repkar","skin","hskin","hhskin","omd","ssoa");UpdateAllFile();UpdatePluginList("kar");