"use strict";var myskinRedrawer={};myskinRedrawer["locateTexFromSkinHead"]=function(skinHead){var getTextureLength=function(){var t=br.tell();br.seek(br.readShortJava());br.seek(21);br.seek(br.readIntJava());var l=br.tell()-t;br.seek(t,0);return l;};var br=new BufferReader(skinHead);var name=br.readUTFJava();var version=0;var pointnum=br.readShortJava();if(pointnum<0){version=pointnum;pointnum=br.readShortJava();}
br.seek(pointnum*4);var hasTexture=br.readByteJava();if(hasTexture){return{"offset":br.tell(),"size":getTextureLength()};}};myskinRedrawer["matchTexFromTexArray"]=function(buffer,texArray,index){var texArrayClass=new ArrayBuffer().fromText("[Lcom.cyberstep.onstage.gfx.Texture");var s=buffer.match(texArrayClass);s+=texArrayClass.byteLength;for(var i=0;i<texArray.length;i++){var tex=texArray[i].toBlockDataJava();s=buffer.match(tex,s);if(s+tex.byteLength>buffer.byteLength){return;}
if(index==i){return{"offset":s,"size":tex.byteLength};}
s+=tex.byteLength;}};myskinRedrawer["getHead"]=function(list){var head="";for(var i=0;i<list.length;i++){var tex;if(list[i]["buffer"]&&list[i]["buffer"].byteLength){var ser=list[i]["buffer"].unserializeSer();if(ser["head"]&&ser["head"].byteLength){var l=myskinRedrawer["locateTexFromSkinHead"](ser["head"]);if(l){tex=new ArrayBuffer().serializeSer("com.cyberstep.onstage.gfx.Texture",{"buffer":ser["head"].getBuffer(l["offset"],l["size"])}).getBase64();}}
if(tex){if(head==""){head=tex;}
else if(head!=tex){head="";break;}}}}
return head;};myskinRedrawer["getFace"]=function(list,index){var face="";for(var i=0;i<list.length;i++){var tex;if(list[i]["buffer"]&&list[i]["buffer"].byteLength){var ser=list[i]["buffer"].unserializeSer();if(ser["face"]&&ser["face"]["tex"]&&ser["face"]["tex"].length&&ser["face"]["tex"][index]&&ser["face"]["tex"][index].byteLength){tex=new ArrayBuffer().serializeSer("com.cyberstep.onstage.gfx.Texture",{"buffer":ser["face"]["tex"][index]}).getBase64();}
if(tex){if(face==""){face=tex;}
else if(face!=tex){face="";break;}}}}
return face;};myskinRedrawer["getFace1"]=function(list){return myskinRedrawer["getFace"](list,0);};myskinRedrawer["getFace2"]=function(list){return myskinRedrawer["getFace"](list,1);};myskinRedrawer["getFace3"]=function(list){return myskinRedrawer["getFace"](list,2);};myskinRedrawer["getFace4"]=function(list){return myskinRedrawer["getFace"](list,3);};myskinRedrawer["getFace5"]=function(list){return myskinRedrawer["getFace"](list,4);};myskinRedrawer["getFace6"]=function(list){return myskinRedrawer["getFace"](list,5);};myskinRedrawer["getFace7"]=function(list){return myskinRedrawer["getFace"](list,6);};myskinRedrawer["getBody"]=function(list){var body="";for(var i=0;i<list.length;i++){var tex;if(list[i]["buffer"]&&list[i]["buffer"].byteLength){var ser=list[i]["buffer"].unserializeSer();if(ser["body"]&&ser["body"]["tex"]&&ser["body"]["tex"].byteLength){tex=new ArrayBuffer().serializeSer("com.cyberstep.onstage.gfx.Texture",{"buffer":ser["body"]["tex"]}).getBase64();}
if(tex){if(body==""){body=tex;}
else if(body!=tex){body="";break;}}}}
return body;};myskinRedrawer["setHead"]=function(buffer,head){if(head){var ser=buffer.unserializeSer();if(ser["head"]&&ser["head"].byteLength){var l=myskinRedrawer["locateTexFromSkinHead"](ser["head"]);if(l){var head0=ser["head"].toBlockDataJava();var head1=new ArrayBuffer().concat(ser["head"].getBuffer(0,l["offset"]),new ArrayBuffer().fromBase64(head).unserializeSer(),ser["head"].getBuffer(l["offset"]+l["size"])).toBlockDataJava();var p=buffer.match(head0);buffer=new ArrayBuffer().concat(buffer.getBuffer(0,p),head1,buffer.getBuffer(p+head0.byteLength));}}}
return buffer.getBuffer();};myskinRedrawer["setFace"]=function(buffer,face,index){if(face){var ser=buffer.unserializeSer();if(ser["face"]&&ser["face"]["tex"]&&ser["face"]["tex"].length&&ser["face"]["tex"][index]&&ser["face"]["tex"][index].byteLength){var l=myskinRedrawer["matchTexFromTexArray"](buffer,ser["face"]["tex"],index);if(l){var face1=new ArrayBuffer().fromBase64(face).unserializeSer().toBlockDataJava();buffer=new ArrayBuffer().concat(buffer.getBuffer(0,l["offset"]),face1,buffer.getBuffer(l["offset"]+l["size"]));}}}
return buffer.getBuffer();};myskinRedrawer["setFace1"]=function(buffer,face){return myskinRedrawer["setFace"](buffer,face,0);};myskinRedrawer["setFace2"]=function(buffer,face){return myskinRedrawer["setFace"](buffer,face,1);};myskinRedrawer["setFace3"]=function(buffer,face){return myskinRedrawer["setFace"](buffer,face,2);};myskinRedrawer["setFace4"]=function(buffer,face){return myskinRedrawer["setFace"](buffer,face,3);};myskinRedrawer["setFace5"]=function(buffer,face){return myskinRedrawer["setFace"](buffer,face,4);};myskinRedrawer["setFace6"]=function(buffer,face){return myskinRedrawer["setFace"](buffer,face,5);};myskinRedrawer["setFace7"]=function(buffer,face){return myskinRedrawer["setFace"](buffer,face,6);};myskinRedrawer["setBody"]=function(buffer,body){if(body){var ser=buffer.unserializeSer();if(ser["body"]&&ser["body"]["tex"]&&ser["body"]["tex"].byteLength){var body0=ser["body"]["tex"].toBlockDataJava();var body1=new ArrayBuffer().fromBase64(body).unserializeSer().toBlockDataJava();var bodyIdName=new ArrayBuffer().concat(new ArrayBuffer().fromText(ser["body"]["bodyid"]).toStringDataJava(),new ArrayBuffer().fromText(ser["body"]["bodyname"]).toStringDataJava());var s=buffer.match(bodyIdName);s+=bodyIdName.byteLength;var p=buffer.match(body0,s);buffer=new ArrayBuffer().concat(buffer.getBuffer(0,p),body1,buffer.getBuffer(p+body0.byteLength));}}
return buffer.getBuffer();};ModList["myskin>myskin"]=ModList["myskin>myskin"]||{};ModList["myskin>myskin"]["option"]=ModList["myskin>myskin"]["option"]||{};ModList["myskin>myskin"]["option"]["head"]="";ModList["myskin>myskin"]["option"]["face1"]="";ModList["myskin>myskin"]["option"]["face2"]="";ModList["myskin>myskin"]["option"]["face3"]="";ModList["myskin>myskin"]["option"]["face4"]="";ModList["myskin>myskin"]["option"]["face5"]="";ModList["myskin>myskin"]["option"]["face6"]="";ModList["myskin>myskin"]["option"]["face7"]="";ModList["myskin>myskin"]["option"]["body"]="";ModList["myskin>myskin"]["getOption"]=ModList["myskin>myskin"]["getOption"]||{};ModList["myskin>myskin"]["getOption"]["head"]=myskinRedrawer["getHead"];ModList["myskin>myskin"]["getOption"]["face1"]=myskinRedrawer["getFace1"];ModList["myskin>myskin"]["getOption"]["face2"]=myskinRedrawer["getFace2"];ModList["myskin>myskin"]["getOption"]["face3"]=myskinRedrawer["getFace3"];ModList["myskin>myskin"]["getOption"]["face4"]=myskinRedrawer["getFace4"];ModList["myskin>myskin"]["getOption"]["face5"]=myskinRedrawer["getFace5"];ModList["myskin>myskin"]["getOption"]["face6"]=myskinRedrawer["getFace6"];ModList["myskin>myskin"]["getOption"]["face7"]=myskinRedrawer["getFace7"];ModList["myskin>myskin"]["getOption"]["body"]=myskinRedrawer["getBody"];ModList["myskin>myskin"]["modData"]=ModList["myskin>myskin"]["modData"]||{};ModList["myskin>myskin"]["modData"]["head"]=myskinRedrawer["setHead"];ModList["myskin>myskin"]["modData"]["face1"]=myskinRedrawer["setFace1"];ModList["myskin>myskin"]["modData"]["face2"]=myskinRedrawer["setFace2"];ModList["myskin>myskin"]["modData"]["face3"]=myskinRedrawer["setFace3"];ModList["myskin>myskin"]["modData"]["face4"]=myskinRedrawer["setFace4"];ModList["myskin>myskin"]["modData"]["face5"]=myskinRedrawer["setFace5"];ModList["myskin>myskin"]["modData"]["face6"]=myskinRedrawer["setFace6"];ModList["myskin>myskin"]["modData"]["face7"]=myskinRedrawer["setFace7"];ModList["myskin>myskin"]["modData"]["body"]=myskinRedrawer["setBody"];UpdateModList();UpdatePluginList("myskinRedrawer");