"use strict";window.settingExporter=function(fileInfo){var buffer=fileInfo.buffer;var entries=[];var empty={"path":"","buffer":new ArrayBuffer(),"time":0};var kar;var Writer=function(){var a=[];this.write=function(k,v){var d=(arguments.length>2?arguments[2]:undefined);if(v!=d){a.push(((k?k+"=":"")+v).replace(/\n/g,"\\n"));}};this.writeHeader=function(v){var l=(arguments.length>1?arguments[1]:true);if(v){this.write("","//");this.write("","//");this.write("","//\t"+(l?v.toLowerCase():v).split("_").map(function(a){return a[0].toUpperCase()+a.slice(1);}).join(" "));this.write("","//");this.write("","//");}
this.write("","");};this.writeFooter=function(){var o=(arguments.length>0?arguments[0]:0);var n=3+o;for(var i=0;i<n;i++){this.write("","");}};this.to=function(){return a.join("\n");};};var getSer=function(t){var files=kar.getEntries();var l=(function(){for(var i=0;i<files.length;i++){if(files[i]["path"]==t){return i;}}
return-1;})();if(l!=-1){kar.checkBuffer(l);return files[l]["buffer"].unserializeSer();}};var indexOf=function(path){for(var i=0;i<entries.length;i++){if(entries[i]["path"]==path){return i;}}
return-1;};var getFolders=function(path){var r=[];var s=0;while(true){var l=path.indexOf("/",s);if(l>0){r.push((r.length?r[r.length-1]:"")+path.slice(s,l+1));s=l;}
s+=1;if(l==-1){break;}}
return r;};var add=function(file){if(file["path"]){while(file["path"][0]=="/"){file["path"]=file["path"].slice(1);}}
var n=-1;var l=indexOf(file["path"]);if(l!=-1){n=l;entries[n]["path"]=(file["path"]?file["path"]:entries[n]["path"]);entries[n]["folders"]=getFolders(entries[n]["path"]);entries[n]["buffer"]=(file["buffer"]?file["buffer"]:entries[n]["buffer"]||empty["buffer"]);entries[n]["time"]=(file["time"]?file["time"]:entries[n]["time"]);}
else{n=entries.length;entries[n]={"index":n,"path":file["path"],"folders":getFolders(file["path"]),"buffer":file["buffer"]||empty["buffer"],"time":file["time"]||empty["time"]};}
var f=[];for(var i=0;i<entries[n]["folders"].length;i++){var l=indexOf(entries[n]["folders"][i]);if(l==-1){f.push({"index":entries.length,"path":entries[n]["folders"][i],"folders":getFolders(entries[n]["folders"][i]),"buffer":empty["buffer"],"time":empty["time"]});}}
if(f.length){entries.inserts(f,n);}};this.addFiles=function(files){for(var i=0;i<files.length;i++){add(files[i]);}
entries=entries.sort(SortPath);for(var i=0;i<entries.length;i++){entries[i]["index"]=i;}
return this;};this.addFile=function(file){this.addFiles([file]);return this;};this.checkBuffer=function(index){entries[index]["buffer"]=(entries[index]["buffer"].byteLength?entries[index]["buffer"]:buffer.getBuffer(entries[index]["offset"],entries[index]["size"]));return entries[index]["buffer"];};this.getEntries=function(){return entries;};this.from=function(buffer){var add=function(path,text,time){if(path&&text){files.push({"index":files.length,"path":path+".unicode","buffer":new ArrayBuffer().fromText(text,"UTF-16",false),"time":time});}};var join=function(a){return(a||[]).join(",");};var files=[];kar=kar||(function(){if(window["Kar"]){return new window["Kar"](new FileInfo(fileInfo.name+"."+fileInfo.ext,buffer));}})();if(kar){var setting=getSer("setting");var dict=getSer("dict");var serverlist=getSer("serverlist");var date=new Date();add("stylesetting",(function(){var w=new Writer();if(setting&&setting["stylegroups"]){if(setting["stylegroups"].length){w.writeHeader("style_group");w.write("stylegroup.num",setting["stylegroups"].length);for(var i=0;i<setting["stylegroups"].length;i++){var s="stylegroup"+(i+1)+".";w.write(s+"id",setting["stylegroups"][i]["id"]);w.write(s+"name",setting["stylegroups"][i]["name"],"");}
w.writeFooter();}}
if(setting&&setting["styles"]){if(setting["styles"].length){var getUseable=function(t){var v=[];var v2=[];t=t||[];for(var i=0;i<t.length;i++){if(t[i]){if(t[i].startsWith("kr_")){v2.push(t[i]);}
else{v.push(t[i]);}}}
return[join(v),join(v2)];};w.writeHeader("style");w.write("style.num",setting["styles"].length);for(var i=0;i<setting["styles"].length;i++){w.write("","");var s="style"+(i+1)+".";w.write(s+"id",setting["styles"][i]["id"]);w.write(s+"name",setting["styles"][i]["name"],"");w.write(s+"path",setting["styles"][i]["path"],"");w.write(s+"desc",setting["styles"][i]["desc"],"");w.write(s+"race",setting["styles"][i]["race"],"");w.write(s+"group",setting["styles"][i]["group"],"");w.write(s+"sex",setting["styles"][i]["sex"]);w.write(s+"STR",setting["styles"][i]["STR"]);w.write(s+"TEC",setting["styles"][i]["TEC"]);w.write(s+"SPD",setting["styles"][i]["SPD"]);w.write(s+"JMP",setting["styles"][i]["JMP"]);w.write(s+"DEF",setting["styles"][i]["DEF"]);w.write(s+"size",setting["styles"][i]["size"]);w.write(s+"advanced",setting["styles"][i]["advanced"],false);w.write(s+"initial",setting["styles"][i]["initial"]);w.write(s+"strongitems",setting["styles"][i]["strongitems"]);w.write(s+"anger",setting["styles"][i]["anger"],1);w.write(s+"grudge",setting["styles"][i]["grudge"],1);var heads=getUseable(setting["styles"][i]["useableheads"]);w.write("","");w.write(s+"heads",heads[0],"");w.write("","");w.write(s+"heads2",heads[1],"");var bodies=getUseable(setting["styles"][i]["useablebodies"]);w.write("","");w.write(s+"bodies",bodies[0],"");w.write("","");w.write(s+"bodies2",bodies[1],"");var accs=getUseable(setting["styles"][i]["useableaccessories"]);w.write("","");w.write(s+"accs",accs[0],"");w.write("","");w.write(s+"accs2",accs[1],"");w.write("","");w.write("","");}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("headsetting",(function(){var w=new Writer();if(setting&&setting["heads"]){var keys=Object.keys(setting["heads"]);if(keys.length){w.writeHeader("head");w.write("head.num",keys.length);for(var i=0;i<keys.length;i++){w.write("","");var s="head"+(i+1)+".";w.write(s+"id",setting["heads"][keys[i]]["id"]);w.write(s+"name",setting["heads"][keys[i]]["name"],"");w.write(s+"icon",setting["heads"][keys[i]]["icon"],"");w.write(s+"path",setting["heads"][keys[i]]["path"],"");w.write(s+"sex",setting["heads"][keys[i]]["sex"],3);w.write(s+"init",setting["heads"][keys[i]]["init"],true);}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("facesetting",(function(){var w=new Writer();if(setting&&setting["races"]){var m=["yellow_male","yellow_female","white_male","white_female","black_male","black_female","android1","android2","hbrute_male","hbrute_female","rival_male","rival_female","gy_male","gy_female"];var t=["ym","yw","wm","ww","bm","bw","and1","and2","bem","bew","am","aw","gym","gyw"];var f=["eye","nose","mouth"];for(var i=0;i<m.length;i++){if(setting["races"][m[i]]){w.writeHeader(m[i]);w.write(t[i]+"."+"id",m[i]);w.write(t[i]+"."+"basetex",setting["races"][m[i]]["basetex"],"");w.write(t[i]+"."+"sex",setting["races"][m[i]]["sex"],3);w.write(t[i]+"."+"facetype",setting["races"][m[i]]["facetype"],0);for(var j=0;j<f.length;j++){var a=setting["races"][m[i]][f[j]+"s"];if(a&&a.length){w.write("","");w.write(t[i]+"."+f[j]+".num",a.length);for(var k=0;k<a.length;k++){w.write("","");var s=t[i]+"."+f[j]+(k+1)+".";w.write(s+"id",a[k]["id"]);w.write(s+"name",a[k]["name"],"");w.write(s+"icon",a[k]["icon"],"");w.write(s+"path",a[k]["path"],"");w.write(s+"init",a[k]["init"],true);}
w.write("","");w.write("","");}}
w.writeFooter();}}}
return w.to();})(),new Date()-date);var date=new Date();add("bodysetting",(function(){var w=new Writer();if(setting&&setting["bodies"]){var keys=Object.keys(setting["bodies"]);if(keys.length){w.writeHeader("body");w.write("body.num",keys.length);for(var i=0;i<keys.length;i++){w.write("","");var s="body"+(i+1)+".";w.write(s+"id",setting["bodies"][keys[i]]["id"]);w.write(s+"name",setting["bodies"][keys[i]]["name"],"");w.write(s+"icon",setting["bodies"][keys[i]]["icon"],"");w.write(s+"path",setting["bodies"][keys[i]]["path"],"");w.write(s+"init",setting["bodies"][keys[i]]["init"],true);}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("accssetting",(function(){var w=new Writer();if(setting&&setting["accs"]){var a=(function(){var v=[];for(var n in setting["accs"]){v.push(setting["accs"][n]);}
v=v.sort(function(a,b){return a["setidx"]-b["setidx"];});return v;})();if(a.length){var toEditable=function(f){var v=[];if(f&0x01){v.push("model");}
if(f&0x02){v.push("texture");}
return v.join(",");};var toMultiaccs=function(v){return["","base","false"][v]||"";};w.writeHeader("accsessory");w.write("accessory.num",a.length);for(var i=0;i<a.length;i++){w.write("","");var s="accessory"+a[i]["setidx"]+".";w.write(s+"id",a[i]["id"]);w.write(s+"name",a[i]["name"],"");w.write(s+"icon",a[i]["icon"],"");w.write(s+"path",a[i]["path"],"");w.write(s+"desc",a[i]["desc"],"");w.write(s+"editable",toEditable(a[i]["editable"]),"");w.write(s+"sex",a[i]["sex"],3);w.write(s+"multiaccs",toMultiaccs(a[i]["multiaccs"]),"");w.write(s+"pcvan",a[i]["pcvan"],false);w.write(s+"slotnum",a[i]["slotnum"],1);}
w.writeFooter();}}
if(setting&&setting["acpolicies"]){var a=(function(){var v=[];for(var n in setting["acpolicies"]){v.push(setting["acpolicies"][n]);}
return v;})();if(a.length){w.writeHeader("accessory_scaling_policy");w.write("aspolicy.num",a.length);for(var i=0;i<a.length;i++){w.write("","");var s="aspolicy"+(i+1)+".";w.write(s+"id",a[i]["id"]);var as=(function(){var v=[];for(var n in a[i]["sizes"]){v.push({"type":n,"size":a[i]["sizes"][n]["value"]});}
return v;})();w.write(s+"body.num",as.length);for(var j=0;j<as.length;j++){w.write(s+"body"+(j+1)+".type",as[j]["type"]);w.write(s+"body"+(j+1)+".size",as[j]["size"]);}}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("itemsetting",(function(){var w=new Writer();if(setting&&setting["items"]){var keys=Object.keys(setting["items"]);if(keys.length){w.writeHeader("item");w.write("item.num",keys.length);for(var i=0;i<keys.length;i++){w.write("","");var s="item"+(i+1)+".";w.write(s+"id",setting["items"][keys[i]]["id"]);w.write(s+"name",setting["items"][keys[i]]["name"],"");w.write(s+"icon",setting["items"][keys[i]]["icon"],"");w.write(s+"path",setting["items"][keys[i]]["path"],"");w.write(s+"desc",setting["items"][keys[i]]["desc"],"");w.write(s+"option",setting["items"][keys[i]]["option"],"");w.write(s+"class",join(setting["items"][keys[i]]["cls"]),"");w.write(s+"sex",setting["items"][keys[i]]["sex"],3);}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("toursetting",(function(){var w=new Writer();if(setting&&setting["rules"]){var keys=Object.keys(setting["rules"]);if(keys.length){w.writeHeader("rule");w.write("rule.num",keys.length);for(var i=0;i<keys.length;i++){w.write("","");var s="rule"+(i+1)+".";w.write(s+"id",setting["rules"][keys[i]]["id"]);w.write(s+"path",setting["rules"][keys[i]]["path"],"");w.write(s+"desc.single",setting["rules"][keys[i]]["singledesc"],"");w.write(s+"desc.team1",setting["rules"][keys[i]]["team1desc"],"");w.write(s+"desc.team2",setting["rules"][keys[i]]["team2desc"],"");}
w.writeFooter();}}
if(setting&&setting["stages"]){var keys=Object.keys(setting["stages"]);if(keys.length){w.writeHeader("stage");w.write("stage.num",keys.length);for(var i=0;i<keys.length;i++){w.write("","");var s="stage"+(i+1)+".";w.write(s+"id",setting["stages"][keys[i]]["id"]);w.write(s+"name",setting["stages"][keys[i]]["name"],"unnamed");w.write(s+"mapdata",setting["stages"][keys[i]]["mapdata"]);w.write(s+"path",setting["stages"][keys[i]]["path"]);w.write(s+"rule",setting["stages"][keys[i]]["rule"]);w.write(s+"time",setting["stages"][keys[i]]["time"],0);w.write(s+"zoomoutmax",setting["stages"][keys[i]]["zoomoutmax"],0);var center=(function(){var br=new BufferReader(setting["stages"][keys[i]]["fixedCameraCenter"]);return[br.readFloat(4,false),br.readFloat(4,false),br.readFloat(4,false),setting["stages"][keys[i]]["fixedCameraZoomOut"],setting["stages"][keys[i]]["fixedCameraLayer"]];})();w.write(s+"center",join(center),"0,0,0,0,0");var options=(function(){var v=[];if(setting["stages"][keys[i]]["optionTable"]){for(var n in setting["stages"][keys[i]]["optionTable"]){v.push({"key":n,"value":setting["stages"][keys[i]]["optionTable"][n]});}}
return v;})();if(options.length){w.write(s+"option.num",options.length,0);for(var j=0;j<options.length;j++){w.write(s+"option"+(j+1),options[j]["key"]+","+options[j]["value"]);}}
var planes=setting["stages"][keys[i]]["guideplane"]||[];if(planes.length){w.write(s+"plane.num",planes.length,0);for(var j=0;j<planes.length;j++){w.write(s+"plane"+j+".x",planes[j]["x"],0);w.write(s+"plane"+j+".y",planes[j]["y"],0);w.write(s+"plane"+j+".z",planes[j]["z"],0);w.write(s+"plane"+j+".w",planes[j]["w"],1);w.write(s+"plane"+j+".d",planes[j]["d"],1);}}
w.write(s+"name4room",setting["stages"][keys[i]]["name4room"],setting["stages"][keys[i]]["name"]);}
w.writeFooter();}}
if(setting&&setting["tours"]){if(setting["tours"].length){var getType=function(t){if((t==3)&&ranking){return"story";}
else{return["normal","team","challenge","amped_survival","team_survival","amped_champ","team_champ"][t];}};var getRanking=function(t,o){var v=join([t,(o?"high":"")]);return(v==","?"":v);};w.writeHeader("tournament");w.write("tournament.num",setting["tours"].length);for(var i=0;i<setting["tours"].length;i++){w.write("","");var s="tournament"+(i+1)+".";w.write(s+"id",setting["tours"][i]["id"]);w.write(s+"name",setting["tours"][i]["name"]);w.write(s+"path",setting["tours"][i]["path"]);w.write(s+"desc",setting["tours"][i]["desc"],"");w.write(s+"initial",setting["tours"][i]["initial"]);w.write(s+"type",getType(setting["tours"][i]["type"]));var ranking=getRanking(setting["tours"][i]["rankingtype"],setting["tours"][i]["rankingorder"]);w.write(s+"ranking",ranking,"");w.write(s+"stagenum",setting["tours"][i]["stagenum"],0);for(var j=0;j<setting["tours"][i]["stagenum"];j++){w.write(s+"stage"+(j+1),join(setting["tours"][i]["stages"][j]["stages"]),"");}
w.write(s+"people",join(setting["tours"][i]["people"]),"");w.write(s+"prize",join(setting["tours"][i]["prizes"]),"");w.write(s+"turbo",setting["tours"][i]["turbo"],0);w.write(s+"item",setting["tours"][i]["itemenabled"],true);w.write(s+"npc",setting["tours"][i]["npcenabled"],true);w.write(s+"anger",setting["tours"][i]["angerenabled"],true);w.write(s+"accslimit",setting["tours"][i]["accslimitenabled"],false);w.write(s+"editable",setting["tours"][i]["editable"],"");w.write(s+"option",setting["tours"][i]["options"],"");w.write(s+"condition",join(setting["tours"][i]["conditions"]),"");w.write(s+"clearindex",(setting["tours"][i]["clearIndexMulti"]?join(setting["tours"][i]["clearIndexMulti"]):setting["tours"][i]["clearIndex"]),"-1");}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("npcsetting",(function(){var w=new Writer();if(setting&&setting["npcs"]){var a=(function(){var v=[];for(var n in setting["npcs"]){v.push(setting["npcs"][n]);}
v=v.sort(function(a,b){return a["id"].localeCompare(b["id"]);});return v;})();if(a.length){w.writeHeader("NPC",false);w.write("npc.num",a.length);for(var i=0;i<a.length;i++){w.write("","");var s="npc"+(i+1)+".";w.write(s+"id",a[i]["id"]);w.write(s+"name",a[i]["name"],"npcname");w.write(s+"isEvent",a[i]["isEvent"],false);w.write(s+"HP",a[i]["HP"],100);w.write(s+"MP",a[i]["MP"],50);w.write(s+"STR",a[i]["STR"],5);w.write(s+"TEC",a[i]["TEC"],5);w.write(s+"SPD",a[i]["SPD"],5);w.write(s+"JMP",a[i]["JMP"],5);w.write(s+"DEF",a[i]["DEF"],5);w.write(s+"size",a[i]["size"],1);w.write(s+"guts",a[i]["guts"],50);w.write(s+"seriousness",a[i]["seriousness"],50);w.write(s+"savagery",a[i]["savagery"],50);w.write(s+"guile",a[i]["guile"],50);w.write(s+"responsibility",a[i]["responsibility"],50);w.write(s+"urgency",a[i]["urgency"],50);w.write(s+"playerdata",a[i]["playerdata"],"");w.write(s+"head",a[i]["headname"],"");w.write(s+"face",a[i]["facename"],"");w.write(s+"body",a[i]["bodyname"],"");w.write(s+"strongitems",a[i]["strongitems"],"");w.write(s+"dropitem",a[i]["dropitem"],"");w.write(s+"stylename",a[i]["stylename"],"");var item=(a[i]["equipment"]?a[i]["equipment"]+(a[i]["equiprate"]?":"+a[i]["equiprate"]:""):"");w.write(s+"item",item,"");w.write(s+"accs",a[i]["accessory"],"");w.write(s+"sacc",a[i]["subAccessory"],"");var tastes=(function(){var v=[];if(a[i]["taste"]){for(var n in a[i]["taste"]){v.push({"key":n,"value":a[i]["taste"][n]});}}
return v;})();if(tastes.length){w.write(s+"taste.num",tastes.length,0);for(var j=0;j<tastes.length;j++){w.write(s+"taste"+(j+1),tastes[j]["key"]+","+tastes[j]["value"]);}}
var serifs=(function(){var v=[];if(a[i]["serif"]){for(var n in a[i]["serif"]){v.push({"key":n,"value":a[i]["serif"][n]});}}
return v;})();if(serifs.length){w.write(s+"serif.num",serifs.length,0);for(var j=0;j<serifs.length;j++){w.write(s+"serif"+(j+1),serifs[j]["key"]+","+serifs[j]["value"]);}}}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("questsetting",(function(){var w=new Writer();if(setting&&setting["quests"]){if(setting["quests"].length){w.writeHeader("quest");w.write("quest.num",setting["quests"].length);for(var i=0;i<setting["quests"].length;i++){w.write("","");var s="quest"+(i+1)+".";w.write(s+"id",setting["quests"][i]["id"]);w.write(s+"name",setting["quests"][i]["name"],"unnamed");w.write(s+"desc",setting["quests"][i]["desc"],"");w.write(s+"prize",setting["quests"][i]["prize"],"");w.write(s+"mission",setting["quests"][i]["mission"],"");}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("etcitemsetting",(function(){var w=new Writer();if(setting&&setting["etcs"]){var keys=Object.keys(setting["etcs"]);if(keys.length){w.writeHeader("ETC Item",false);w.write("etcitem.num",keys.length);for(var i=0;i<keys.length;i++){if(setting["etcs"][keys[i]]["id"].startsWith("emotion")&&(setting["etcs"][keys[i]]["icon"]=="/icon/etc/emotion.tex")){continue;}
w.write("","");var s="etcitem"+(i+1)+".";w.write(s+"id",setting["etcs"][keys[i]]["id"]);w.write(s+"name",setting["etcs"][keys[i]]["name"],"");w.write(s+"icon",setting["etcs"][keys[i]]["icon"],"");w.write(s+"desc",setting["etcs"][keys[i]]["desc"],"");w.write(s+"bicon",setting["etcs"][keys[i]]["bigIcon"],"");if(!isUndefined(setting["etcs"][keys[i]]["neednum"])){w.write(s+"neednum",join(setting["etcs"][keys[i]]["neednum"]),"");}
if(!isUndefined(setting["etcs"][keys[i]]["bonusnum"])){w.write(s+"bonusnum",join(setting["etcs"][keys[i]]["bonusnum"]),"");}
if(!isUndefined(setting["etcs"][keys[i]]["meter"])){w.write(s+"meter",setting["etcs"][keys[i]]["meter"],"");}
if(!isUndefined(setting["etcs"][keys[i]]["onceFree"])){w.write(s+"oncefree",setting["etcs"][keys[i]]["onceFree"],false);}
if(!isUndefined(setting["etcs"][keys[i]]["onceFreePCVAN"])){w.write(s+"oncefreepcvan",setting["etcs"][keys[i]]["onceFreePCVAN"],false);}}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("generalsetting",(function(){var w=new Writer();if(setting&&setting["version"]){w.writeHeader("general_setting");w.write("general.version",setting["version"]);w.write("","");w.write("general.totalrankings","scorerank,killerrank,fsrank,musclerank");w.write("general.stylerankings","scorerank,killerrank,fsrank,musclerank");w.writeFooter();}
if(setting&&setting["prizes"]){if(setting["prizes"].length){w.writeHeader("special_prize");w.write("prize.num",setting["prizes"].length);for(var i=0;i<setting["prizes"].length;i++){w.write("","");var s="prize"+(i+1)+".";w.write(s+"id",setting["prizes"][i]["id"]);w.write(s+"name",setting["prizes"][i]["name"],"unnamed");w.write(s+"icon",setting["prizes"][i]["icon"],"");w.write(s+"class",setting["prizes"][i]["classname"],"");w.write(s+"score",setting["prizes"][i]["score"],0);w.write(s+"color",join(setting["prizes"][i]["color"]),"1,1,1,1");}
w.writeFooter();}}
if(setting&&setting["rankings"]){if(setting["rankings"].length){w.writeHeader("ranking");w.write("ranking.num",setting["rankings"].length);for(var i=0;i<setting["rankings"].length;i++){w.write("","");var s="ranking"+(i+1)+".";w.write(s+"id",setting["rankings"][i]["id"]);w.write(s+"name",setting["rankings"][i]["name"],"unnamed");w.write(s+"unit",setting["rankings"][i]["unit"],"unnamed");w.write(s+"type",setting["rankings"][i]["type"],"unnamed");w.write(s+"point",setting["rankings"][i]["point"],"unnamed");w.write(s+"where",setting["rankings"][i]["where"],"");w.write(s+"order",setting["rankings"][i]["order"],"");w.write(s+"limit",setting["rankings"][i]["limit"],1000);}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("valuesetsetting",(function(){var w=new Writer();if(setting&&setting["valuesets"]){var a=(function(){var v=[];for(var n in setting["valuesets"]){v.push(setting["valuesets"][n]);}
return v;})();if(a.length){w.writeHeader("value_set");w.write("set.num",a.length);for(var i=0;i<a.length;i++){w.write("","");var s="set"+(i+1)+".";w.write(s+"id",a[i]["id"]);w.write(s+"name",a[i]["name"],"");w.write(s+"icon",a[i]["icon"],"");w.write(s+"desc",a[i]["desc"],"");w.write(s+"bicon",a[i]["bigIcon"],"");w.write(s+"sex",a[i]["sex"],3);}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("survivalsetting",(function(){var w=new Writer();var k=["svtour","survival","svprize","spprize","prizeset"];if(setting&&setting["svtours"]){w.writeHeader("survival_tournament");var amped=setting["svtours"][k[1]+"defauttournamentinfo_amped"];if(amped&&amped["stagetypes"].length&&amped["defratio"].length){w.write(k[0]+".amped.type",join(amped["stagetypes"]),"");w.write(k[0]+".amped.ratio",join(amped["defratio"]),"");w.write("","");}
var team=setting["svtours"][k[1]+"defauttournamentinfo_team"];if(team&&team["stagetypes"].length&&team["defratio"].length){w.write(k[0]+".team.type",join(team["stagetypes"]),"");w.write(k[0]+".team.ratio",join(team["defratio"]),"");w.write("","");}
var a=(function(){var v=[];for(var n in setting["svtours"]){if(n.startsWith(k[1]+"_")){v.push(setting["svtours"][n]);}}
return v;})();if(a.length){w.write(k[0]+".num",a.length);for(var i=0;i<a.length;i++){w.write("","");var s=k[0]+(i+1)+".";w.write(s+"id",a[i]["id"]);w.write(s+"path",a[i]["path"],"");w.write(s+"team",a[i]["isTeam"],false);if(a[i]["stagetypes"].length){w.write(s+"stagetypenum",a[i]["stagetypes"].length,0);for(var j=0;j<a[i]["stagetypes"].length;j++){w.write(s+"stagetype"+(j+1),a[i]["stagetypes"][j],"");}}
w.write(s+"stage.ratio",join(a[i]["defratio"]),"");if(a[i]["offsets"].length){w.write(s+"stage.ratio.offset.num",a[i]["offsets"].length,0);for(var j=0;j<a[i]["offsets"].length;j++){w.write(s+"stage.ratio.offset"+(j+1),a[i]["offsets"][j],"");}}}}
w.writeFooter();}
if(setting&&setting["svprizes"]){var a=(function(){var v=[];for(var n in setting["svprizes"]){v.push(setting["svprizes"][n]);}
v=v.sort(function(a,b){return a["id"].localeCompare(b["id"]);});return v;})();if(a.length){w.writeHeader("survival_prize");w.write(k[2]+".num",a.length);for(var i=0;i<a.length;i++){w.write("","");var s=k[2]+(i+1)+".";w.write(s+"id",a[i]["id"]);w.write(s+"name",a[i]["name"],"");w.write(s+"desc",a[i]["desc"],"");w.write(s+"prize",a[i]["prize"],"");}
w.writeFooter();}}
if(setting&&setting["svspprizes"]){var keys=Object.keys(setting["svspprizes"]);if(keys.length){w.writeHeader("survival_special_prize");w.write(k[3]+".num",keys.length);for(var i=0;i<keys.length;i++){w.write("","");var s=k[3]+(i+1)+".";w.write(s+"id",setting["svspprizes"][keys[i]]["id"]);w.write(s+"name",setting["svspprizes"][keys[i]]["name"],"");w.write(s+"desc",setting["svspprizes"][keys[i]]["desc"],"");if(setting["svspprizes"][keys[i]]["conds"].length){w.write(s+"cond.num",setting["svspprizes"][keys[i]]["conds"].length,0);for(var j=0;j<setting["svspprizes"][keys[i]]["conds"].length;j++){w.write(s+"cond"+(j+1),setting["svspprizes"][keys[i]]["conds"][j],"");}}}
w.writeFooter();}}
if(setting&&(setting["gmprizesets"]||setting["_gmprizesets"])){w.writeHeader("survival_prize_set_GM",false);var set=(setting["gmprizesets"]||setting["_gmprizesets"]);var m=["m2m","guild","gm"];for(var c=0;c<m.length;c++){var num=(set[m[c]+".maxwin.num"]?set[m[c]+".maxwin.num"]["value"]:0);if(num){w.write(m[c]+"."+k[4]+".num",num,0);w.write("","");for(var i=0;i<=num;i++){var prize=set[m[c]+"."+k[4]+i+".prize"];if(prize){w.write(m[c]+"."+k[4]+i+".prize",prize["prize"],"");if(prize["specials"].length){w.write(m[c]+"."+k[4]+i+".special.num",prize["specials"].length,0);for(var j=0;j<prize["specials"].length;j++){w.write(m[c]+"."+k[4]+i+".special"+(j+1),prize["specials"][j],"");}}}}
w.write("","");}}
w.writeFooter();}
if(setting&&(setting["rmprizesets"]||setting["_rmprizesets"])){w.writeHeader("survival_prize_set_RM",false);var set=(setting["rmprizesets"]||setting["_rmprizesets"]);var m=["m2mhardcore","rm"];for(var c=0;c<m.length;c++){var num=(set[m[c]+".maxwin.num"]?set[m[c]+".maxwin.num"]["value"]:0);if(num){w.write(m[c]+"."+k[4]+".num",num,0);w.write("","");for(var i=0;i<=num;i++){var prize=set[m[c]+"."+k[4]+i+".prize"];if(prize){w.write(m[c]+"."+k[4]+i+".prize",prize["prize"],"");if(prize["specials"].length){w.write(m[c]+"."+k[4]+i+".special.num",prize["specials"].length,0);for(var j=0;j<prize["specials"].length;j++){w.write(m[c]+"."+k[4]+i+".special"+(j+1),prize["specials"][j],"");}}}}
w.write("","");}}
w.writeFooter();}
return w.to();})(),new Date()-date);var date=new Date();add("guildexsetting",(function(){var w=new Writer();if(setting&&(setting["guildmemberclasses"]||setting["guildmemberclassgmratios"])){var a=(function(){var o={};if(setting["guildmemberclasses"]){for(var n in setting["guildmemberclasses"]){o[n]=o[n]||{};o[n]["id"]=setting["guildmemberclasses"][n]["id"];o[n]["name"]=setting["guildmemberclasses"][n]["name"];o[n]["icon"]=setting["guildmemberclasses"][n]["icon"];o[n]["authority"]=setting["guildmemberclasses"][n]["authority"];o[n]["level"]=setting["guildmemberclasses"][n]["level"];}}
if(setting["guildmemberclassgmratios"]){for(var n in setting["guildmemberclassgmratios"]){o[n]=o[n]||{};o[n]["id"]=n;o[n]["gmratio"]=setting["guildmemberclassgmratios"][n]["value"];}}
var v=[];for(var n in o){v.push(o[n]);}
v=v.sort(function(a,b){return a["level"]-b["level"];});return v;})();if(a.length){var getAuthority=function(t){var v=[];var m=["icon","kick","invite"];var b=new ArrayBuffer().fromArray([t]).getBits();for(var i=0;i<m.length;i++){if(b.getUint8(i)){v.push(m[i]);}}
return v.join(",");};w.writeHeader("guild_class");w.write("guild.class.num",a.length);for(var i=0;i<a.length;i++){w.write("","");var s="guild.class"+(i+1)+".";w.write(s+"id",a[i]["id"]);w.write(s+"name",a[i]["name"],"");w.write(s+"icon",a[i]["icon"],"");w.write(s+"authority",getAuthority(a[i]["authority"]),"");w.write(s+"gmratio",a[i]["gmratio"],0);}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("attribute",(function(){var w=new Writer();if(setting&&setting["attribute"]){var a=(function(){var v=[];for(var n in setting["attribute"]){v.push(setting["attribute"][n]);}
return v;})();if(a.length){w.writeHeader("attribute");w.write("attri.num",a.length);for(var i=0;i<a.length;i++){w.write("","");var s="attri"+(i+1)+".";w.write(s+"id",a[i]["id"]);if(!isUndefined(a[i]["x"])){w.write(s+"x",a[i]["x"],0);}
if(!isUndefined(a[i]["y"])){w.write(s+"y",a[i]["y"],0);}
if(!isUndefined(a[i]["x_m"])){w.write(s+"x_m",a[i]["x_m"],0);}
if(!isUndefined(a[i]["y_m"])){w.write(s+"y_m",a[i]["y_m"],0);}
if(!isUndefined(a[i]["path"])){w.write(s+"path",a[i]["path"],"");}}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("emotionsetting",(function(){var w=new Writer();if(setting&&setting["emotions"]){if(setting["emotions"].length){w.writeHeader("emotion");w.write("emotion.num",setting["emotions"].length);for(var i=0;i<setting["emotions"].length;i++){w.write("","");var s="emotion"+i+".";w.write(s+"id",setting["emotions"][i]["id"]);w.write(s+"name",setting["emotions"][i]["name"],"");w.write(s+"path",setting["emotions"][i]["path"],"");w.write(s+"grade",setting["emotions"][i]["grade"],0);}
w.writeFooter();}}
if(setting&&setting["emoticons"]){if(setting["emoticons"].length){w.writeHeader("emoticon");w.write("emoticon.num",setting["emoticons"].length);for(var i=0;i<setting["emoticons"].length;i++){w.write("","");var s="emoticon"+i+".";w.write(s+"id",setting["emoticons"][i]["id"]);w.write(s+"name",setting["emoticons"][i]["name"],"");w.write(s+"icon",setting["emoticons"][i]["icon"],"");if(setting["emoticons"][i]["path"].length){w.write(s+"path.num",setting["emoticons"][i]["path"].length,0);for(var j=0;j<setting["emoticons"][i]["path"].length;j++){w.write(s+"path"+(j+1),setting["emoticons"][i]["path"][j],"");}}
w.write(s+"time",setting["emoticons"][i]["time"],1000);w.write(s+"loop",setting["emoticons"][i]["loop"],false);w.write(s+"grade",setting["emoticons"][i]["grade"],0);}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("champsetting",(function(){var w=new Writer();var k=["chtour","champ","chprize","chspprize","chprizeset"];var ch={"min":10,"max":20};if(setting&&setting["champTours"]){w.writeHeader("champ_tournament");for(var c=ch["min"];c<ch["max"];c++){var amped=setting["champTours"][c]["ch"+c+"."+k[1]+"defauttournamentinfo_amped"];if(amped&&amped["stagetypes"].length&&amped["defratio"].length){w.write("ch"+c+"."+k[0]+".amped.type",join(amped["stagetypes"]),"");w.write("ch"+c+"."+k[0]+".amped.ratio",join(amped["defratio"]),"");w.write("","");}
var team=setting["champTours"][c]["ch"+c+"."+k[1]+"defauttournamentinfo_team"];if(team&&team["stagetypes"].length&&team["defratio"].length){w.write("ch"+c+"."+k[0]+".team.type",join(team["stagetypes"]),"");w.write("ch"+c+"."+k[0]+".team.ratio",join(team["defratio"]),"");w.write("","");}}
for(var c=ch["min"];c<ch["max"];c++){var a=(function(){var v=[];for(var n in setting["champTours"][c]){if(n.startsWith(k[1]+"_")){v.push(setting["champTours"][c][n]);}}
return v;})();if(a.length){w.write("ch"+c+"."+k[0]+".num",a.length,0);for(var i=0;i<a.length;i++){w.write("","");var s="ch"+c+"."+k[0]+(i+1)+".";w.write(s+"id",a[i]["id"]);w.write(s+"path",a[i]["path"],"");w.write(s+"team",a[i]["isTeam"],false);if(a[i]["stagetypes"].length){w.write(s+"stagetypenum",a[i]["stagetypes"].length,0);for(var j=0;j<a[i]["stagetypes"].length;j++){w.write(s+"stagetype"+(j+1),a[i]["stagetypes"][j],"");}}
w.write(s+"stage.ratio",join(a[i]["defratio"]),"");if(a[i]["offsets"].length){w.write(s+"stage.ratio.offset.num",a[i]["offsets"].length,0);for(var j=0;j<a[i]["offsets"].length;j++){w.write(s+"stage.ratio.offset"+(j+1),a[i]["offsets"][j],"");}}}
w.write("","");}}
w.writeFooter();}
if(setting&&setting["champPrizes"]){var list=(function(){var l=[];for(var c=ch["min"];c<ch["max"];c++){var v=[];if(setting["champPrizes"][c]){for(var n in setting["champPrizes"][c]){v.push({"id":setting["champPrizes"][c][n]["id"],"name":setting["champPrizes"][c][n]["name"],"desc":setting["champPrizes"][c][n]["desc"],"prize":setting["champPrizes"][c][n]["prize"]});}}
v=v.sort(function(a,b){return a["id"].localeCompare(b["id"]);});l[c]=v;}
return l;})();if(list.some(function(a){return a.length;})){w.writeHeader("champ_prize");for(var c=ch["min"];c<ch["max"];c++){if(list[c].length){w.write("c"+c+"."+k[2]+".num",list[c].length,0);for(var i=0;i<list[c].length;i++){w.write("","");var s="c"+c+"."+k[2]+(i+1)+".";w.write(s+"id",list[c][i]["id"]);w.write(s+"name",list[c][i]["name"],"");w.write(s+"desc",list[c][i]["desc"],"");w.write(s+"prize",list[c][i]["prize"],"");}
w.write("","");}}
w.writeFooter();}}
if(setting&&setting["champSpPrizes"]){var list=(function(){var l=[];for(var c=ch["min"];c<ch["max"];c++){l[c]=Object.keys((setting["champSpPrizes"][c]||{}));}
return l;})();if(list.some(function(a){return a.length;})){w.writeHeader("champ_special_prize");for(var c=ch["min"];c<ch["max"];c++){if(list[c].length){w.write("ch"+c+"."+k[3]+".num",list[c].length,0);for(var i=0;i<list[c].length;i++){w.write("","");var s="ch"+c+"."+k[3]+(i+1)+".";w.write(s+"id",setting["champSpPrizes"][c][list[c][i]]["id"]);w.write(s+"name",setting["champSpPrizes"][c][list[c][i]]["name"],"");w.write(s+"desc",setting["champSpPrizes"][c][list[c][i]]["desc"],"");if(setting["champSpPrizes"][c][list[c][i]]["conds"].length){w.write(s+"cond.num",setting["champSpPrizes"][c][list[c][i]]["conds"].length,0);for(var j=0;j<setting["champSpPrizes"][c][list[c][i]]["conds"].length;j++){w.write(s+"cond"+(j+1),setting["champSpPrizes"][c][list[c][i]]["conds"][j],"");}}}
w.write("","");}}
w.writeFooter();}}
if(setting&&setting["champPrizeSets"]){var list=(function(){var l=[];for(var c=ch["min"];c<ch["max"];c++){l[c]=setting["champPrizeSets"][c];}
return l;})();if(list.some(function(a){return a.length;})){w.writeHeader("champ_prize_set");for(var c=ch["min"];c<ch["max"];c++){if(list[c].length){w.write("ch"+c+"."+k[4]+".num",list[c].length,0);for(var i=0;i<list[c].length;i++){w.write("","");w.write("ch"+c+"."+k[4]+i+".prize",list[c][i]["prize"],"");if(list[c][i]["specials"].length){w.write("ch"+c+"."+k[4]+i+".special.num",list[c][i]["specials"].length,0);for(var j=0;j<list[c][i]["specials"].length;j++){w.write("ch"+c+"."+k[4]+i+".special"+(j+1),list[c][i]["specials"][j],"");}}}
w.write("","");}}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("randomentry",(function(){var w=new Writer();if(setting&&setting["randomEntrys"]){if(setting["randomEntrys"].length){w.writeHeader("random_entry");w.write("randomentry.num",setting["randomEntrys"].length);for(var i=0;i<setting["randomEntrys"].length;i++){w.write("","");var s="randomentry"+i+".";w.write(s+"id",setting["randomEntrys"][i]["id"]);w.write(s+"name",setting["randomEntrys"][i]["name"],"");w.write(s+"desc",setting["randomEntrys"][i]["desc"],"");w.write(s+"id.amped",setting["randomEntrys"][i]["idAmped"],"");w.write(s+"id.team",setting["randomEntrys"][i]["idTeam"],"");}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("newplayersetting",(function(){var w=new Writer();if(setting&&setting["newplayer"]){w.writeHeader("new_player");w.write("newplayer.accs",join(setting["newplayer"]["accsId"]),"");w.write("","");w.write("newplayer.item",join(setting["newplayer"]["itemId"]),"");w.write("newplayer.item.num",setting["newplayer"]["itemNum"],0);w.write("","");w.write("newplayer.num",setting["newplayer"]["newPlayerStyleSetList"].length,0);for(var i=0;i<setting["newplayer"]["newPlayerStyleSetList"].length;i++){w.write("","");var s="newplayer.style"+(i+1)+".";w.write(s+"id",setting["newplayer"]["newPlayerStyleSetList"][i]["styleId"],"");w.write(s+"head",join(setting["newplayer"]["newPlayerStyleSetList"][i]["headId"]),"");w.write(s+"body",join(setting["newplayer"]["newPlayerStyleSetList"][i]["bodyId"]),"");w.write(s+"eye",join(setting["newplayer"]["newPlayerStyleSetList"][i]["eyeId"]),"");w.write(s+"nose",join(setting["newplayer"]["newPlayerStyleSetList"][i]["noseId"]),"");w.write(s+"mouth",join(setting["newplayer"]["newPlayerStyleSetList"][i]["mouthId"]),"");}
w.writeFooter();}
return w.to();})(),new Date()-date);var date=new Date();add("myroomsetting",(function(){var w=new Writer();if(setting&&setting["furnitures"]){var keys=Object.keys(setting["furnitures"]);if(keys.length){var getType=function(t){var m=["","room","wall","base","ride"];return m[t]||"";};w.writeHeader("furniture");w.write("furniture.num",keys.length);for(var i=0;i<keys.length;i++){w.write("","");var s="furniture"+(i+1)+".";w.write(s+"id",setting["furnitures"][keys[i]]["id"]);w.write(s+"name",setting["furnitures"][keys[i]]["name"],"");w.write(s+"icon",setting["furnitures"][keys[i]]["icon"],"");w.write(s+"path",setting["furnitures"][keys[i]]["path"],"");w.write(s+"desc",setting["furnitures"][keys[i]]["desc"],"");w.write(s+"type",getType(setting["furnitures"][keys[i]]["type"]),"");}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("cardsetting",(function(){var w=new Writer();if(setting&&setting["customizecard"]){var a=(function(){var v=[];for(var n in setting["customizecard"]){v.push(setting["customizecard"][n]);}
v=v.sort(function(a,b){return a["id"].localeCompare(b["id"]);});return v;})();if(a.length){var getEffect=function(t){var v=[];if(t&&t.length){for(var i=0;i<t.length;i++){if(t[i]&&t[i]["effectid"]){v.push(t[i]["effectid"]+(t[i]["odds"]?":"+t[i]["odds"]:""));}}}
return v;};w.writeHeader("card");w.write("card.num",a.length);for(var i=0;i<a.length;i++){w.write("","");var s="card"+(i+1)+".";w.write(s+"id",a[i]["id"]);w.write(s+"name",a[i]["name"],"");w.write(s+"icon",a[i]["icon"],"");w.write(s+"desc",a[i]["desc"],"");w.write(s+"effect",getEffect(a[i]["elements"]),"");w.write(s+"excustomaccs",join(a[i]["excustomaccs"]),"");w.write(s+"grade",a[i]["priceGrade"],0);}
w.writeFooter();}}
if(setting&&setting["customizeeffect"]){var a=(function(){var v=[];for(var n in setting["customizeeffect"]){v.push(setting["customizeeffect"][n]);}
v=v.sort(function(a,b){return a["id"].localeCompare(b["id"]);});return v;})();if(a.length){w.writeHeader("effect");w.write("effect.num",a.length);for(var i=0;i<a.length;i++){w.write("","");var s="effect"+(i+1)+".";w.write(s+"id",a[i]["id"]);w.write(s+"amount",join(a[i]["amount"])+"."+a[i]["scale"],"");w.write(s+"amount2",join(a[i]["amount2"]),"0,0,0,0,0,0,0,0,0,0");w.write(s+"amount3",join(a[i]["amount3"]),"0,0,0,0");w.write(s+"strongitems",a[i]["strongitems"],"");if(!isUndefined(a[i]["rank"])){w.write(s+"rank",a[i]["rank"]);}
if(!isUndefined(a[i]["needs"])){w.write(s+"needs",a[i]["needs"],"");}
if(!isUndefined(a[i]["result"])){w.write(s+"result",join(a[i]["result"]),"");}
if(!isUndefined(a[i]["ratio"])){w.write(s+"ratio",join(a[i]["ratio"]),"");}}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("dailyquestsetting",(function(){var w=new Writer();if(setting&&setting["dailyquests"]){if(setting["dailyquests"].length){w.writeHeader("daily_quest");w.write("dailyquest.num",setting["dailyquests"].length);for(var i=0;i<setting["dailyquests"].length;i++){w.write("","");var s="dailyquest"+(i+1)+".";w.write(s+"id",setting["dailyquests"][i]["id"]);w.write(s+"name",setting["dailyquests"][i]["name"],"");w.write(s+"desc",setting["dailyquests"][i]["desc"],"");w.write(s+"prize",setting["dailyquests"][i]["prize"],"");}
w.writeFooter();}}
if(setting&&setting["prizegroups"]){if(setting["prizegroups"].length){w.writeHeader("prize_group");w.write("prizegroup.num",setting["prizegroups"].length);for(var i=0;i<setting["prizegroups"].length;i++){w.write("","");var s="prizegroup"+(i+1)+".";w.write(s+"id",setting["prizegroups"][i]["id"]);w.write(s+"prize",setting["prizegroups"][i]["prize"],"");w.write(s+"ratio",setting["prizegroups"][i]["ratio"],"");w.write(s+"dupindex",setting["prizegroups"][i]["dupindex"],1);}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("treasureboxsetting",(function(){var w=new Writer();if(setting&&setting["treasureboxes"]){var a=(function(){var v=[];for(var n in setting["treasureboxes"]){v.push(setting["treasureboxes"][n]);}
v=v.sort(function(a,b){return a["id"].localeCompare(b["id"]);});return v;})();if(a.length){w.writeHeader("treasure_box");w.write("treasurebox.num",a.length);for(var i=0;i<a.length;i++){w.write("","");var s="treasurebox"+(i+1)+".";w.write(s+"id",a[i]["id"]);w.write(s+"name",a[i]["name"],"");w.write(s+"icon",a[i]["icon"],"");w.write(s+"desc",a[i]["desc"],"");w.write(s+"icon.open",a[i]["icono"],"");w.write(s+"icon.close",a[i]["iconc"],"");w.write(s+"exp",a[i]["exp"],0);w.write(s+"exp.type",a[i]["type"],"");w.write(s+"prize",join(a[i]["prize"]),"");w.write(s+"ratio",join(a[i]["ratio"]),"");w.write(s+"dupindex",join(a[i]["dupindex"]),"");w.write(s+"announce",join(a[i]["announce"]),"");w.write(s+"tournament",a[i]["tournament"],"");w.write(s+"accessory",a[i]["accessory"],"");w.write(s+"style",a[i]["style"],"");w.write(s+"secret",a[i]["secret"],false);}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("pcvansetting",(function(){var w=new Writer();if(setting&&setting["pcvan"]){var write=function(t,premium){w.write((premium?"pcvan.premium."+t:"pcvan."+t),(premium?join(setting["pcvan"]["pcvan.premium."+t]):join(setting["pcvan"]["pcvan."+t])),"");};w.writeHeader("PC-VAN",false);var m=["style","head","eye","nose","mouth","body","skin","accs","subaccs"];for(var i=0;i<m.length;i++){w.write("","");write(m[i],false);}
for(var i=0;i<m.length;i++){w.write("","");write(m[i],true);}
w.writeFooter();}
return w.to();})(),new Date()-date);var date=new Date();add("couponsetting",(function(){var w=new Writer();if(setting&&setting["coupons"]){var a=(function(){var v=[];for(var n in setting["coupons"]){v.push(setting["coupons"][n]);}
v=v.sort(function(a,b){return a["id"].localeCompare(b["id"]);});return v;})();if(a.length){w.writeHeader("coupon");w.write("coupon.num",a.length);for(var i=0;i<a.length;i++){w.write("","");var s="coupon"+(i+1)+".";w.write(s+"id",a[i]["id"]);w.write(s+"name",a[i]["name"],"");w.write(s+"icon",a[i]["icon"],"");w.write(s+"desc",a[i]["desc"],"");w.write(s+"type",a[i]["type"],0);w.write(s+"value",a[i]["value"],0);w.write(s+"period",a[i]["period"],0);w.write(s+"present",a[i]["present"],"");w.write(s+"shopcategory",join(a[i]["category"]),"");}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("emblemsetting",(function(){var w=new Writer();if(setting&&setting["emblems"]){var a=(function(){var v=[];for(var n in setting["emblems"]){v.push(setting["emblems"][n]);}
v=v.sort(function(a,b){return a["id"].localeCompare(b["id"]);});return v;})();if(a.length){var getEffect=function(t){var v=[];for(var n in t){if(t[n]["effectid"]&&t[n]["odds"]){v.push(t[n]["effectid"]+":"+t[n]["odds"]);}}
return v.join(",");};w.writeHeader("emblem");w.write("emblem.num",a.length);for(var i=0;i<a.length;i++){w.write("","");var s="emblem"+(i+1)+".";w.write(s+"id",a[i]["id"]);w.write(s+"name",a[i]["name"],"");w.write(s+"icon",a[i]["icon"],"");w.write(s+"desc",a[i]["desc"],"");w.write(s+"effect",getEffect(a[i]["elements"]),"");w.write(s+"condition",join(a[i]["condition"]),"");w.write(s+"get_type",join(a[i]["get_type"]),"");w.write(s+"get_msg",a[i]["msg"],"");w.write(s+"icon.num",a[i]["iconmax"],0);for(var j=0;j<a[i]["icons"].length;j++){w.write(s+"icon"+(j+1),a[i]["icons"][j],"");}
w.write(s+"anim",join(a[i]["animtime"]),"");}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("designcombinesetting",(function(){var w=new Writer();if(setting&&setting["designcombines"]){if(setting["designcombines"].length){w.writeHeader("design_combine");w.write("designcombine.num",setting["designcombines"].length);for(var i=0;i<setting["designcombines"].length;i++){w.write("","");var s="designcombine"+(i+1)+".";w.write(s+"id",setting["designcombines"][i]["id"]);w.write(s+"name",setting["designcombines"][i]["name"],"");w.write(s+"mate",join(setting["designcombines"][i]["materials"]),"");w.write(s+"prize",join(setting["designcombines"][i]["prizes"]),"");w.write(s+"ratio",join(setting["designcombines"][i]["ratios"]),"");w.write(s+"dupindex",join(setting["designcombines"][i]["dupindex"]),"");}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("collectionsetting",(function(){var w=new Writer();if(setting&&setting["collectionbooks"]){if(setting["collectionbooks"].length){w.writeHeader("collection_book");w.write("collection.num",setting["collectionbooks"].length);for(var i=0;i<setting["collectionbooks"].length;i++){w.write("","");var s="collection"+(i+1)+".";w.write(s+"id",setting["collectionbooks"][i]["id"]);w.write(s+"name",setting["collectionbooks"][i]["name"],"");w.write(s+"icon",setting["collectionbooks"][i]["icon"],"");w.write(s+"desc",setting["collectionbooks"][i]["desc"],"");w.write(s+"level",setting["collectionbooks"][i]["level"],"");w.write(s+"list",setting["collectionbooks"][i]["list"],"");w.write(s+"condition",join(setting["collectionbooks"][i]["condition"]),"");w.write(s+"prize",setting["collectionbooks"][i]["prize"],"");w.write(s+"duplicate",setting["collectionbooks"][i]["duplicate"],"");}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("newcombinesetting",(function(){var w=new Writer();if(setting&&setting["newcombines"]){if(setting["newcombines"].length){w.writeHeader("new_combine");w.write("newcombine.num",setting["newcombines"].length);for(var i=0;i<setting["newcombines"].length;i++){w.write("","");var s="newcombine"+(i+1)+".";w.write(s+"id",setting["newcombines"][i]["id"]);w.write(s+"name",setting["newcombines"][i]["name"],"");w.write(s+"mate",join(setting["newcombines"][i]["materials"]),"");w.write(s+"prize",join(setting["newcombines"][i]["prizes"]),"");w.write(s+"ratio",join(setting["newcombines"][i]["ratios"]),"");w.write(s+"dupindex",join(setting["newcombines"][i]["dupindex"]),"");w.write(s+"preview",setting["newcombines"][i]["showpreview"],true);w.write(s+"announce",join(setting["newcombines"][i]["announce"]),"");w.write(s+"saveindex",join(setting["newcombines"][i]["svindex"]),"");w.write(s+"savemate",join(setting["newcombines"][i]["svmate"]),"");w.write(s+"category",setting["newcombines"][i]["category"],0);w.write(s+"keepcustom",setting["newcombines"][i]["keepcustom"],"");if(setting["newcombines"][i]["ranknum"]){w.write(s+"ranknum",setting["newcombines"][i]["ranknum"],0);for(var j=0;j<setting["newcombines"][i]["rankmaterials"].length;j++){w.write(s+"rankmate"+(j+1),join(setting["newcombines"][i]["rankmaterials"][j]),"");}}}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("subaccssetting",(function(){var w=new Writer();if(setting&&setting["subaccs"]){var a=(function(){var v=[];for(var n in setting["subaccs"]){v.push(setting["subaccs"][n]);}
v=v.sort(function(a,b){return a["setidx"]-b["setidx"];});return v;})();if(a.length){var toEditable=function(f){var v=[];if(f&0x01){v.push("model");}
if(f&0x02){v.push("texture");}
return v.join(",");};var toMultiaccs=function(v){return["","base","false"][v]||"";};w.writeHeader("sub_accessory",false);w.write("subaccessory.num",a.length);for(var i=0;i<a.length;i++){w.write("","");var s="subaccessory"+a[i]["setidx"]+".";w.write(s+"id",a[i]["id"]);w.write(s+"name",a[i]["name"],"");w.write(s+"icon",a[i]["icon"],"");w.write(s+"path",a[i]["path"],"");w.write(s+"desc",a[i]["desc"],"");w.write(s+"editable",toEditable(a[i]["editable"]),"");w.write(s+"sex",a[i]["sex"],3);w.write(s+"multiaccs",toMultiaccs(a[i]["multiaccs"]),"");w.write(s+"pcvan",a[i]["pcvan"],false);w.write(s+"slotnum",a[i]["slotnum"],1);}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("bquestsetting",(function(){var w=new Writer();if(setting&&setting["battleQuest"]){w.writeHeader("battle_quest");w.write("bquest.tournament",join(setting["battleQuest"]["tournaments"]),"");w.write("bquest.tournament.ratio",setting["battleQuest"]["incidenceRatio"],0);w.write("bquest.table",join(setting["battleQuest"]["table"]),"");w.write("bquest.ratio",join(setting["battleQuest"]["ratio"]),"");w.write("","");if(setting["battleQuest"]["list"].length){w.write("bquest.num",setting["battleQuest"]["list"].length);for(var i=0;i<setting["battleQuest"]["list"].length;i++){w.write("","");var s="bquest"+(i+1)+".";w.write(s+"id",setting["battleQuest"]["list"][i]["cond"]);w.write(s+"name",setting["battleQuest"]["list"][i]["name"],"");w.write(s+"desc",setting["battleQuest"]["list"][i]["desc"],"");w.write(s+"prize",join(setting["battleQuest"]["list"][i]["prizes"]),"");w.write(s+"ratio",join(setting["battleQuest"]["list"][i]["ratios"]),"");w.write(s+"dupindex",join(setting["battleQuest"]["list"][i]["dupindex"]),"0");}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("helplibrarysetting",(function(){var w=new Writer();if(setting&&setting["helplibraries"]){if(setting["helplibraries"].length){w.writeHeader("help_librarie");w.write("helplibrary.num",setting["helplibraries"].length);for(var i=0;i<setting["helplibraries"].length;i++){w.write("","");var s="helplibrary"+(i+1)+".";w.write(s+"id",setting["helplibraries"][i]["id"]);w.write(s+"title",setting["helplibraries"][i]["title"],"");w.write(s+"parent",setting["helplibraries"][i]["parent"],"");if(setting["helplibraries"][i]["components"].length){w.write(s+"component.num",setting["helplibraries"][i]["components"].length,0);for(var j=0;j<setting["helplibraries"][i]["components"].length;j++){w.write(s+"component"+(j+1)+".image",setting["helplibraries"][i]["components"][j][0],"");w.write(s+"component"+(j+1)+".desc",setting["helplibraries"][i]["components"][j][1],"");}}}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("newquestsetting",(function(){var w=new Writer();if(setting&&setting["newQuests"]){if(setting["newQuests"].length){w.writeHeader("new_quest");w.write("newquest.num",setting["newQuests"].length);for(var i=0;i<setting["newQuests"].length;i++){w.write("","");var s="newquest"+(i+1)+".";w.write(s+"id",setting["newQuests"][i]["id"]);w.write(s+"name",setting["newQuests"][i]["name"],"unnamed");w.write(s+"icon",setting["newQuests"][i]["icon"],"");w.write(s+"desc",setting["newQuests"][i]["desc"],"");w.write(s+"level",setting["newQuests"][i]["level"]);w.write(s+"prize",setting["newQuests"][i]["prize"],"");w.write(s+"condition",setting["newQuests"][i]["condition"],"");w.write(s+"repeat",setting["newQuests"][i]["repeat"],false);}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("loginluckysetting",(function(){var w=new Writer();if(setting&&setting["loginLuckySets"]){var a=(function(){var v=[];for(var n in setting["loginLuckySets"]){v.push(setting["loginLuckySets"][n]);}
v=v.sort(function(a,b){return a["id"].localeCompare(b["id"]);});return v;})();if(a.length){w.writeHeader("login_lucky");w.write("loginlucky.num",a.length);for(var i=0;i<a.length;i++){w.write("","");var s="loginlucky"+(i+1)+".";w.write(s+"id",a[i]["id"]);w.write(s+"max",a[i]["max"],0);w.write(s+"ratio",a[i]["ratio"],0);if(a[i]["setting"]){if(!isUndefined(a[i]["setting"]["prize"])){w.write(s+"prize",a[i]["setting"]["prize"],"");}
if(!isUndefined(a[i]["setting"]["msg"])){w.write(s+"msg",a[i]["setting"]["msg"],"");}
if(!isUndefined(a[i]["setting"]["pmsg"])){w.write(s+"pmsg",a[i]["setting"]["pmsg"],"");}
if(!isUndefined(a[i]["setting"]["announce"])){w.write(s+"announce",a[i]["setting"]["announce"],"");}}
var m=["prize","msg","announce"];for(var j=0;j<32767;j++){for(var k=0;k<m.length;k++){var ss=m[k]+(j+1);if(!isUndefined(a[i]["setting"][ss])){w.write(s+ss,a[i]["setting"][ss],"");}}}}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("missionsetting",(function(){var w=new Writer();if(setting&&setting["hmissions2"]){var a=(function(){var v=[];for(var n in setting["hmissions2"]){v.push(setting["hmissions2"][n]);}
v=v.sort(function(a,b){return a["num"]-b["num"];});return v;})();if(a.length){var getAbility=function(t){var m=["GUT","SER","SAV","GUI","RES","URG"];return m[t]||"";};var getSymbol=function(t){var m=["==",">=","<="];return m[t]||"";};w.writeHeader("hunter_mission");w.write("mission.num",a.length);for(var i=0;i<a.length;i++){w.write("","");var s="mission"+(i+1)+".";w.write(s+"id",a[i]["id"]);w.write(s+"name",a[i]["name"],"");w.write(s+"icon",a[i]["icon"],"");w.write(s+"desc",a[i]["desc"],"");w.write(s+"desc.success",a[i]["successdesc"],"");w.write(s+"rank",a[i]["rank"],"");w.write(s+"cp.num",a[i]["cpDesc"].length,0);for(var j=0;j<a[i]["cpDesc"].length;j++){w.write(s+"cp"+(j+1),a[i]["cpDesc"][j]+","+getAbility(a[i]["cpability"][j])+getSymbol(a[i]["cpsymbol"][j])+a[i]["cpvalue"][j],"");}
w.write(s+"time",a[i]["time"]);w.write(s+"success",a[i]["success"]);w.write(s+"cost",a[i]["cost"],"");w.write(s+"exp",a[i]["exp"]);w.write(s+"prize.id",join(a[i]["prize"]),"");w.write(s+"prize.ratio",join(a[i]["ratio"]),"");w.write(s+"list.ratio",a[i]["listratio"]);w.write(s+"cond",join(a[i]["condition"]),"");w.write(s+"onlyonce",a[i]["onlyonce"]);w.write(s+"accsbonus",a[i]["accsbonus"],100);w.write(s+"itembonus",a[i]["itembonus"],100);}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("mapobjectsetting",(function(){var w=new Writer();if(setting&&setting["mapobjects"]){var a=(function(){var v=[];for(var n in setting["mapobjects"]){v.push(setting["mapobjects"][n]);}
v=v.sort(function(a,b){return a["id"].localeCompare(b["id"]);});return v;})();if(a.length){var getType=function(t){var v=[];var m=["basemap","base","ride","player","wall","center"];var b=new ArrayBuffer().fromArray([t]).getBits();for(var i=0;i<m.length;i++){if(b.getUint8(i)){v.push(m[i]);}}
return v.join(",");};w.writeHeader("map_object");w.write("mapobject.num",a.length);for(var i=0;i<a.length;i++){w.write("","");var s="mapobject"+(i+1)+".";w.write(s+"id",a[i]["id"]);w.write(s+"name",a[i]["name"],"");w.write(s+"icon",a[i]["icon"],"");w.write(s+"path",a[i]["path"],"");w.write(s+"desc",a[i]["desc"],"");w.write(s+"type",getType(a[i]["type"]),"");w.write(s+"cost",a[i]["cost"],0);}
w.writeFooter();}}
return w.to();})(),new Date()-date);var date=new Date();add("chatfilter",(function(){var w=new Writer();if(dict&&dict["chatfilter"]){if(dict["chatfilter"].length){for(var i=0;i<dict["chatfilter"].length;i++){w.write("",dict["chatfilter"][i],"");}
w.write("","");}}
if(dict&&dict["specialCharacters"]){if(dict["specialCharacters"].length){w.write("","//SPECIALCHARACTER");for(var i=0;i<dict["specialCharacters"].length;i++){w.write("",dict["specialCharacters"][i]["value"]);}
w.write("","");}}
if(dict&&dict["equalFilter"]){if(dict["equalFilter"].length){w.write("","//EQUALFILTER");for(var i=0;i<dict["equalFilter"].length;i++){w.write("",dict["equalFilter"][i],"");}
w.write("","");}}
return w.to();})(),new Date()-date);var date=new Date();add("charnamefilter",(function(){var w=new Writer();if(dict&&dict["charnamefilter"]){if(dict["charnamefilter"].length){for(var i=0;i<dict["charnamefilter"].length;i++){w.write("",dict["charnamefilter"][i],"");}
w.write("","");}}
return w.to();})(),new Date()-date);var date=new Date();add("dic",(function(){var w=new Writer();if(dict&&dict["map"]){var a=(function(){var v=[];for(var n in dict["map"]){v.push({"key":n,"value":dict["map"][n]});}
v=v.sort(function(a,b){return a["key"].localeCompare(b["key"]);});return v;})();if(a.length){for(var i=0;i<a.length;i++){w.write(a[i]["key"],a[i]["value"],"");}
w.write("","");}}
return w.to();})(),new Date()-date);var date=new Date();add("servers",(function(){var w=new Writer();if(serverlist&&serverlist["map"]){var num=parseInt(serverlist["map"]["entrance.num"]);if(!isNaN(num)&&num){w.writeHeader("entrance");w.write("entrance.num",num);for(var i=0;i<num;i++){w.write("","");var _id="entrance"+(i+1)+".id";w.write(_id,serverlist["map"][_id]);var _num="entrance"+(i+1)+".num";if(serverlist["map"][_num]){var n=parseInt(serverlist["map"][_num]);if(!isNaN(n)&&n){w.write(_num,serverlist["map"][_num]);for(var j=0;j<n;j++){var ss="entrance"+(i+1)+"_"+j;var ss1="entrance"+(i+1)+"_"+(j+1);w.write(ss,serverlist["map"][ss1]);}}}}}
w.writeFooter();}
return w.to();})(),new Date()-date);entries=[];this.addFiles(files);}
return this;};if(buffer.byteLength){this.from(buffer);}};EtcMatch=Object.assign({"settingExporter":function(fileInfo){return(fileInfo.nameCore.indexOf("setting")!=-1)&&(fileInfo.ext=="kar");}},EtcMatch);UpdatePluginList("settingExporter");