"use strict";window.settingAnalyzer_mission=function(fileInfo){var buffer=fileInfo.buffer;var entries=[];var empty={"path":"","buffer":new ArrayBuffer(),"time":0};var kar;var Writer=function(){var a=[];this.write=function(){var v=[];for(var i=0;i<arguments.length;i++){v[i]=arguments[i];}
a.push(v.join("\t"));};this.to=function(){return a.join("\r\n");};};var getSer=function(t){var files=kar.getEntries();var l=(function(){for(var i=0;i<files.length;i++){if(files[i]["path"]==t){return i;}}
return-1;})();if(l!=-1){kar.checkBuffer(l);return files[l]["buffer"].unserializeSer();}};var indexOf=function(path){for(var i=0;i<entries.length;i++){if(entries[i]["path"]==path){return i;}}
return-1;};var getFolders=function(path){var r=[];var s=0;while(true){var l=path.indexOf("/",s);if(l>0){r.push((r.length?r[r.length-1]:"")+path.slice(s,l+1));s=l;}
s+=1;if(l==-1){break;}}
return r;};var add=function(file){if(file["path"]){while(file["path"][0]=="/"){file["path"]=file["path"].slice(1);}}
var n=-1;var l=indexOf(file["path"]);if(l!=-1){n=l;entries[n]["path"]=(file["path"]?file["path"]:entries[n]["path"]);entries[n]["folders"]=getFolders(entries[n]["path"]);entries[n]["buffer"]=(file["buffer"]?file["buffer"]:entries[n]["buffer"]||empty["buffer"]);entries[n]["time"]=(file["time"]?file["time"]:entries[n]["time"]);}
else{n=entries.length;entries[n]={"index":n,"path":file["path"],"folders":getFolders(file["path"]),"buffer":file["buffer"]||empty["buffer"],"time":file["time"]||empty["time"]};}
var f=[];for(var i=0;i<entries[n]["folders"].length;i++){var l=indexOf(entries[n]["folders"][i]);if(l==-1){f.push({"index":entries.length,"path":entries[n]["folders"][i],"folders":getFolders(entries[n]["folders"][i]),"buffer":empty["buffer"],"time":empty["time"]});}}
if(f.length){entries.inserts(f,n);}};this.addFiles=function(files){for(var i=0;i<files.length;i++){add(files[i]);}
entries=entries.sort(SortPath);for(var i=0;i<entries.length;i++){entries[i]["index"]=i;}
return this;};this.addFile=function(file){this.addFiles([file]);return this;};this.checkBuffer=function(index){entries[index]["buffer"]=(entries[index]["buffer"].byteLength?entries[index]["buffer"]:buffer.getBuffer(entries[index]["offset"],entries[index]["size"]));return entries[index]["buffer"];};this.getEntries=function(){return entries;};this.from=function(buffer){var add=function(path,text,time){if(path&&text){files.push({"index":files.length,"path":path+".txt","buffer":new ArrayBuffer().fromText(text,"UTF-16",false),"time":time});}};var files=[];kar=kar||(function(){if(window["Kar"]){return new window["Kar"](new FileInfo(fileInfo.name+"."+fileInfo.ext,buffer));}})();if(kar){var setting=getSer("setting");if(setting&&setting["hmissions2"]&&setting["accs"]&&setting["items"]){var mission=(function(){var v=[];for(var n in setting["hmissions2"]){v.push(setting["hmissions2"][n]);}
v=v.sort(function(a,b){return a["num"]-b["num"];});return v;})();var accs=(function(){var v=[];for(var n in setting["accs"]){v.push(setting["accs"][n]);}
v=v.sort(function(a,b){return a["setidx"]-b["setidx"];});return v;})();var item=(function(){var v=[];for(var n in setting["items"]){v.push(setting["items"][n]);}
v=v.sort(function(a,b){return a["id"].localeCompare(b["id"]);});return v;})();if(mission.length){var accsTotal={};var itemTotal={};var calcBonus=function(id,missionId,bonus){var hash=Math.abs((missionId+id).hashCodeJava());if(hash%100<bonus){return(hash/100%10+1).toAccurated();}
return 1;};for(var i=0;i<mission.length;i++){var accsBonus=(function(){var v=[];for(var j=0;j<accs.length;j++){v.push({"id":accs[j]["id"],"name":accs[j]["name"],"bonus":calcBonus(accs[j]["id"],mission[i]["id"],mission[i]["accsbonus"])});}
v=v.sort(function(a,b){return(b["bonus"]-a["bonus"])||a["id"].localeCompare(b["id"]);});return v;})();if(accsBonus.length){var date=new Date();add(mission[i]["id"]+"-"+mission[i]["name"]+"-accs",(function(){var w=new Writer();w.write("id","name","bonus");for(var j=0;j<accsBonus.length;j++){w.write(accsBonus[j]["id"],accsBonus[j]["name"],accsBonus[j]["bonus"]);accsTotal[accsBonus[j]["id"]]=accsTotal[accsBonus[j]["id"]]||{"id":accsBonus[j]["id"],"name":accsBonus[j]["name"],"bonus":[]};accsTotal[accsBonus[j]["id"]]["bonus"].push(accsBonus[j]["bonus"]);}
return w.to();})(),new Date()-date);}
var itemBonus=(function(){var v=[];for(var j=0;j<item.length;j++){v.push({"id":item[j]["id"],"name":item[j]["name"],"bonus":calcBonus(item[j]["id"],mission[i]["id"],mission[i]["itembonus"])});}
v=v.sort(function(a,b){return(b["bonus"]-a["bonus"])||a["id"].localeCompare(b["id"]);});return v;})();if(itemBonus.length){var date=new Date();add(mission[i]["id"]+"-"+mission[i]["name"]+"-item",(function(){var w=new Writer();w.write("id","name","bonus");for(var j=0;j<itemBonus.length;j++){w.write(itemBonus[j]["id"],itemBonus[j]["name"],itemBonus[j]["bonus"]);itemTotal[itemBonus[j]["id"]]=itemTotal[itemBonus[j]["id"]]||{"id":itemBonus[j]["id"],"name":itemBonus[j]["name"],"bonus":[]};itemTotal[itemBonus[j]["id"]]["bonus"].push(itemBonus[j]["bonus"]);}
return w.to();})(),new Date()-date);}}
accsTotal=(function(){var v=[];for(var id in accsTotal){v.push({"id":accsTotal[id]["id"],"name":accsTotal[id]["name"],"bonus":((accsTotal[id]["bonus"].reduce(function(t,a){return t+a},0)/accsTotal[id]["bonus"].length*100)|0)/100});}
v=v.sort(function(a,b){return(b["bonus"]-a["bonus"])||a["id"].localeCompare(b["id"]);});return v;})();if(accsTotal.length){var date=new Date();add("[average]-accs",(function(){var w=new Writer();w.write("id","name","bonus");for(var i=0;i<accsTotal.length;i++){w.write(accsTotal[i]["id"],accsTotal[i]["name"],accsTotal[i]["bonus"]);}
return w.to();})(),new Date()-date);}
itemTotal=(function(){var v=[];for(var id in itemTotal){v.push({"id":itemTotal[id]["id"],"name":itemTotal[id]["name"],"bonus":((itemTotal[id]["bonus"].reduce(function(t,a){return t+a},0)/itemTotal[id]["bonus"].length*100)|0)/100});}
v=v.sort(function(a,b){return(b["bonus"]-a["bonus"])||a["id"].localeCompare(b["id"]);});return v;})();if(itemTotal.length){var date=new Date();add("[average]-item",(function(){var w=new Writer();w.write("id","name","bonus");for(var i=0;i<itemTotal.length;i++){w.write(itemTotal[i]["id"],itemTotal[i]["name"],itemTotal[i]["bonus"]);}
return w.to();})(),new Date()-date);}}}
entries=[];this.addFiles(files);}
return this;};if(buffer.byteLength){this.from(buffer);}};EtcMatch=Object.assign({"settingAnalyzer_mission":function(fileInfo){return(fileInfo.nameCore.indexOf("setting")!=-1)&&(fileInfo.ext=="kar");}},EtcMatch);UpdatePluginList("settingAnalyzer_mission");